### ISSUE TITLE
List all properties from unknown tdms

### ISSUE THREAD

**Issue by senovr** [adamreeve/npTDMS#103]
HI, 
The structure of the tdms file is pretty flexible regarding the properties that can be written into it.
Is there is a way to iterate through root object, a group object, and channels to retrieve all of the properties (even better with values) that were assigned by the file creator?
I tried such piece of code:
for i in range (0,len(all_files),1):
    tdms_file = TdmsFile(all_files[i])
    for group in tdms_file.groups():
        group_name=group
        print(group_name)
        print(TdmsFile.object(group_name).properties)

and it throws an error:
Traceback (most recent call last):

  File "<ipython-input-10-4ed0e76de0cd>", line 7, in <module>
    print(TdmsFile.object(group_name).properties)

  File "C:\Users\sparkhonyuk\AppData\Local\Continuum\anaconda3\envs\DeepLearning\lib\site-packages\nptdms\tdms.py", line 153, in object
    object_path = self._path(*path)

AttributeError: 'str' object has no attribute '_path'

**Comment by adamreeve** [comment]
Hi, I think the problem is you're trying to call the object method using the class name `TdmsFile` instead of your `tdms_file` instance. This should work:
```python
for i in range (0,len(all_files),1):
    tdms_file = TdmsFile(all_files[i])
    for group in tdms_file.groups():
        group_name=group
        print(group_name)
        print(tdms_file.object(group_name).properties)
```
