### ISSUE TITLE
Strange isinstance behaviour in pandas int and np.int64

### ISSUE THREAD

**Issue by kelupa** [adamreeve/npTDMS#104]
Hi,
I'm trying to convert a simple dataframe with integer values. But when it is the moment to write the file, 

[isinstance(value, int)](https://github.com/adamreeve/npTDMS/blob/master/nptdms/writer.py#L277)

the result of "isinstance(value, int)" is False.   Value is **int64**

It seems that the error is 

[strange-isinstance-behaviour-in-pandas-int-and-np-int64](https://stackoverflow.com/questions/49882785/strange-isinstance-behaviour-in-pandas-int-and-np-int64)

[how-to-determine-if-a-number-is-any-type-of-int-core-or-numpy-signed-or-not](https://stackoverflow.com/questions/37726830/how-to-determine-if-a-number-is-any-type-of-int-core-or-numpy-signed-or-not)

**Comment by adamreeve** [comment]
Apologies for not responding to this previously, this should be fixed now by #153
