### ISSUE TITLE
File reading time depending of the source of the .tdms

### ISSUE THREAD

**Issue by baudoux** [adamreeve/npTDMS#107]
I am using the library to fuse two files generated by two synchronized NI DAQ devices (using the python library nidaqmx)
I read both files, and create a new file combining both
Opening a file generated by the setup takes several minutes, whereas opening the fused file takes few seconds, even though it is bigger.

An example of smaller files is here, I don't see what makes so much difference between file_1 and fused_file
https://drive.google.com/open?id=15zAv_SwzzdVMtKvJBhjxEvGLr-LtyTMu

I don't know where this computation time comes from, would there be a workaround to speedup reading as done on the generated file?

**Comment by ba05** [comment]
Could it be the fused file has been defragged, causing it to open faster?

**Comment by baudoux** [comment]
This is more than probable, I don't know how to check this.
The fused file is still bigger in size, shouldn't it be smaller if it is defragged?
If it is the case, should I rather search how to generate a defragged file with nidaqmx library?

**Comment by baudoux** [comment]
Ok, thank you for your answer, it's very instructive!
Then all the improvement I can do is on the acquisition side, I will try to reduce the number of segments.
