### ISSUE TITLE
New official release on pip

### ISSUE THREAD

**Issue by gregstarr** [adamreeve/npTDMS#108]
Hi, great job on this package, it is very useful and performant. I need to use version 0.13 because of its support of strings, but the latest version on pip is 0.11. Could you make a release of version 0.13 on pip?

Thanks!

**Comment by adamreeve** [comment]
Hi, version 0.13 should already be available from pip, see https://pypi.org/project/npTDMS/0.13.0/. You may need to run `pip install --upgrade npTDMS` if you already have an older version installed.
