### ISSUE TITLE
Writing to TDMS Files?

### ISSUE THREAD

**Issue by seden** [adamreeve/npTDMS#11]
There is exactly one Python module right now, cTDMS(which uses the NI dll) to write TDMS files. Would it be possible to implement writing to a TDMS file in npTDMS? Or is there some constraint (technical or otherwise) that I'm missing?

I have no problem implementing it myself, if there is no issue in doing it. I just don't want to spend a lot of effort and then bang up against some insurmountable roadblock that I don't know about. Any pointers?

**Comment by seb5g** [comment]
Hello,
I've been using your module very easily (so thanks) but now I'm missing the possibilities to save data on my tdms file. Could you tell me if there has been progress on this issue lately?

**Comment by adamreeve** [comment]
Hi. No sorry, nobody is working on this and I don't have any plans to.

**Comment by adamreeve** [comment]
I've started working on this and have an initial implementation in the `tdms-writing` branch, so I'll reopen this issue.

**Comment by phidahl** [comment]
Hi,
I just want say, that write support for npTDMS would be awesome! :) Is the tdms-writing branch in a state where I could already test some things and provide feedback?

**Comment by adamreeve** [comment]
Hi, yeah it should be usable enough to start testing so that would be great if you could try it out and give some feedback. I haven't updated the documentation but there's an example of how to use it at https://github.com/adamreeve/npTDMS/blob/47e6c741655f660a752ae950cd4a68c9662630e9/nptdms/test/writer/acceptance_tests.py

**Comment by seb5g** [comment]
Hello Adam,
I started testing the writing, and have two main comments (well I don't know if here is the place for that):
1) when you create the tdmswriter object from an existing file, the code as it is will override the file and just create a "fresh" file containing only the new objects you've put in it. I changed the options in the open method using a "ab" at the place of "wb". It seems to work!
2) there is no method for deleting groups or channel in existing file. An quick an mybe dirty solution I came up with is to create a temporary file and writing in it all the contents of the tdms object (from my original file). Writing all except the group or channel I don't want. See the code:

`group_to_remove="group1";

with tempfile.TemporaryFile() as temp:
    
    file_path="...\\test.tdms";
    tdms=TdmsFile(file_path)
    with TdmsWriter(temp) as tdms_writer:
        groups=tdms.groups();
        for group in groups:
            if group!=group_to_remove:
                channels=tdms.group_channels(group);
                tdms_writer.write_segment([channels]);
                

    file_name = temp.name;
    shutil.copy(file_name, file_path)`
 what do you think?
Sebastien

**Comment by seb5g** [comment]
I've encountered another issue:
the tdmsobject in the TdmsWriter and in the TdmsFile don't have the same definition, for the first one, "path" is a method while for the second, "path" is a property. This is misleading when you want to write an object you didn't create with the writer method but from the tdmsfile.object method... don't know if this is clear...
Seb

**Comment by adamreeve** [comment]
Thanks for the feedback @seb5g. I don't think it makes sense for 'ab' to be the default file writing mode but I'll add an option to allow appending to an existing file. I'll also take a look at making a TdmsObject read from a file able to be used when writing, that's not something I'd considered but it would obviously be very useful.

**Comment by adamreeve** [comment]
@seb5g, I've made some updates on the tdms-writing branch to address your comments, please let me know if you find any other issues. You can now use `TdmsWriter(path, 'a')` to open a file in append mode. And a TdmsObject read from a file is now compatible with writing to a file, so your example of removing a group will work.
