### ISSUE TITLE
numpy_data_types collision

### ISSUE THREAD

**Issue by rfried** [adamreeve/npTDMS#112]
the npTDMS classes DaqMxRawData and Int16 share the numpy_data_type "np.int16"

https://github.com/adamreeve/npTDMS/blob/526dc3997709409c755d5dd1dc91840759c2be04/nptdms/types.py#L86-L87

https://github.com/adamreeve/npTDMS/blob/526dc3997709409c755d5dd1dc91840759c2be04/nptdms/types.py#L227-L228

Due to the decorator definition:
https://github.com/adamreeve/npTDMS/blob/526dc3997709409c755d5dd1dc91840759c2be04/nptdms/types.py#L32-L33

and due to the order of the npTDMS classes in types.py... DaqMxRawData will supercede Int16 when reading the data_type of a tdms_object. 
https://github.com/adamreeve/npTDMS/blob/526dc3997709409c755d5dd1dc91840759c2be04/nptdms/writer.py#L244-L247

This is unfortunate because sometimes Int16 is the desired type. Though they are both packed the same, the enum written to the segment header is different.

**Comment by adamreeve** [comment]
This should have been fixed in #132, the DAQmx scaler data type is now read from the DAQmx metadata rather than being hard coded as Int16.
