### ISSUE TITLE
Read the metadata/properties of the channels

### ISSUE THREAD

**Issue by GuruManoj** [adamreeve/npTDMS#129]
Hi!
Is it possible to read only the metadata/properties of channels instead of reading all the raw data?

I have large files, is it possible to read only the metadata/properties of channels of the file without reading the raw data because it is taking much time to read all the data where I need only the metadata of the file

**Comment by adamreeve** [comment]
Hi, this isn't possible at the moment but wouldn't be hard to implement as the metadata is already read first in one pass before the data is read.

**Comment by GuruManoj** [comment]
I have referenced this feature in pull request #130.

**Comment by adamreeve** [comment]
I've released version 0.17.0 with this change

**Comment by GuruManoj** [comment]
Thanks!
