### ISSUE TITLE
Could you share a release planning to the community ?

### ISSUE THREAD

**Issue by alexandreCameron** [adamreeve/npTDMS#179]
Hi,

Thank you for this package, it really helps me a lot with my current project.

I use a renovate bot ( https://github.com/renovatebot/renovate ) to automatically update the package versions. Recently, `npTDMS` has been popping frequently for updates. Which is great new, because it means the package is alive and maintained. I especially like the new format used to get 'properties' and 'channels' which is much more python friendly.

Do you have a release schedule to share to the community to help us integrated more easily the updates of the new versions? Do you plan to do a release every week in the future? Are there patches scheduled in your release planning or are the tags all stable?

Thanks again for the great job you're doing :)

**Comment by adamreeve** [comment]
Hi,

Thanks, I'm glad you find this package useful!

I don't have much of a formal release process, there aren't usually very frequent changes needed so I tend to make a release soon after any new changes.

There has been a flurry of releases recently as I hadn't been keeping on top of issues for a while, but have had some time recently to go through the backlog of issues and fix some things, as well as fix things that were bothering me (making the API more intuitive and Pythonic). Releases should slow down again now that's done, as I don't have any other big changes planned.

I've also not been great at guaranteeing backwards compatibility previously, but I intend to release a 1.0.0 version soon after removing the deprecated methods and will then move to semantic versioning releases (patch version increments for bug fixes, minor version increments for new non-breaking features and major version increments for any breaking changes). This means there shouldn't be any work needed to integrate a new release unless there's a new major version released. Any big changes planned should also have a GitHub issue associated so people can see what's being worked on.

**Comment by alexandreCameron** [comment]
Thanks
