### ISSUE TITLE
tdmsfile.groups() returning empty list, 

### ISSUE THREAD

**Issue by icare4-rapla** [adamreeve/npTDMS#18]
H I Adam,
tdmsfile.groups() returns with [] 
tdmsinfo.main() stops too early for -P and -D shows strange floating point data for wf_start_offset
tdms_file.object('high','MEMS 1') works fine
*********************_start file -P
/
properties:
description: T&M Signal Logger
datetime: 2012-01-02 10:20:31.549620
author: 10.127.10.228
version: V2.3.7
lastdatetime: 2012-01-02 10:30:30.549620
name: 3404911229_00005723_03433203_1_228.tdms
campaign_timestamp: 2011-11-23 16:40:28.549620
seq_id: 5723
***_*************_end  file -P
***_*************_start file -D
DEBUG:nptdms.tdms:Reading segment at 0
DEBUG:nptdms.tdms:Property kTocDAQmxRawData is False
DEBUG:nptdms.tdms:Property kTocNewObjList is True
DEBUG:nptdms.tdms:Property kTocInterleavedData is False
DEBUG:nptdms.tdms:Property kTocRawData is False
DEBUG:nptdms.tdms:Property kTocMetaData is True
DEBUG:nptdms.tdms:Property kTocBigEndian is False
DEBUG:nptdms.tdms:Reading metadata at 28
DEBUG:nptdms.tdms:Reading metadata for object /
DEBUG:nptdms.tdms:Object has no data in this segment
DEBUG:nptdms.tdms:Reading 0 properties
DEBUG:nptdms.tdms:Reading segment at 45
DEBUG:nptdms.tdms:Property kTocDAQmxRawData is False
DEBUG:nptdms.tdms:Property kTocNewObjList is True
DEBUG:nptdms.tdms:Property kTocInterleavedData is False
DEBUG:nptdms.tdms:Property kTocRawData is False
DEBUG:nptdms.tdms:Property kTocMetaData is True
DEBUG:nptdms.tdms:Property kTocBigEndian is False
DEBUG:nptdms.tdms:Reading metadata at 73
DEBUG:nptdms.tdms:Reading metadata for object /
DEBUG:nptdms.tdms:Object has no data in this segment
DEBUG:nptdms.tdms:Reading 1 properties
DEBUG:nptdms.tdms:Property description: T&M Signal Logger
DEBUG:nptdms.tdms:Reading segment at 130
DEBUG:nptdms.tdms:Property kTocDAQmxRawData is False
DEBUG:nptdms.tdms:Property kTocNewObjList is True
DEBUG:nptdms.tdms:Property kTocInterleavedData is False
DEBUG:nptdms.tdms:Property kTocRawData is False
DEBUG:nptdms.tdms:Property kTocMetaData is True
DEBUG:nptdms.tdms:Property kTocBigEndian is False
DEBUG:nptdms.tdms:Reading metadata at 158
DEBUG:nptdms.tdms:Reading metadata for object /
DEBUG:nptdms.tdms:Object has no data in this segment
DEBUG:nptdms.tdms:Reading 1 properties
DEBUG:nptdms.tdms:Property datetime: 2012-01-02 10:20:31.549620
DEBUG:nptdms.tdms:Reading segment at 207
DEBUG:nptdms.tdms:Property kTocDAQmxRawData is False
DEBUG:nptdms.tdms:Property kTocNewObjList is True
DEBUG:nptdms.tdms:Property kTocInterleavedData is False
DEBUG:nptdms.tdms:Property kTocRawData is False
DEBUG:nptdms.tdms:Property kTocMetaData is True
DEBUG:nptdms.tdms:Property kTocBigEndian is False
DEBUG:nptdms.tdms:Reading metadata at 235
DEBUG:nptdms.tdms:Reading metadata for object /
DEBUG:nptdms.tdms:Object has no data in this segment
DEBUG:nptdms.tdms:Reading 1 properties
DEBUG:nptdms.tdms:Property author: 10.127.10.228
DEBUG:nptdms.tdms:Reading segment at 283
DEBUG:nptdms.tdms:Property kTocDAQmxRawData is False
DEBUG:nptdms.tdms:Property kTocNewObjList is True
DEBUG:nptdms.tdms:Property kTocInterleavedData is False
DEBUG:nptdms.tdms:Property kTocRawData is False
DEBUG:nptdms.tdms:Property kTocMetaData is True
DEBUG:nptdms.tdms:Property kTocBigEndian is False
DEBUG:nptdms.tdms:Reading metadata at 311
DEBUG:nptdms.tdms:Reading metadata for object /
DEBUG:nptdms.tdms:Object has no data in this segment
DEBUG:nptdms.tdms:Reading 1 properties
DEBUG:nptdms.tdms:Property version: V2.3.7
DEBUG:nptdms.tdms:Reading segment at 353
DEBUG:nptdms.tdms:Property kTocDAQmxRawData is False
DEBUG:nptdms.tdms:Property kTocNewObjList is True
DEBUG:nptdms.tdms:Property kTocInterleavedData is False
DEBUG:nptdms.tdms:Property kTocRawData is True
DEBUG:nptdms.tdms:Property kTocMetaData is True
DEBUG:nptdms.tdms:Property kTocBigEndian is False
DEBUG:nptdms.tdms:Reading metadata at 381
DEBUG:nptdms.tdms:Reading metadata for object /'high'/'Signal 0'
DEBUG:nptdms.tdms:Object data type: tdsTypeSingleFloat
DEBUG:nptdms.tdms:Object number of values in segment: 5120
DEBUG:nptdms.tdms:Reading 16 properties
DEBUG:nptdms.tdms:Property wf_time_pref: absolute
DEBUG:nptdms.tdms:Property wf_start_time: 2012-01-02 10:20:32.549620
DEBUG:nptdms.tdms:Property wf_start_offset: 1.683945893e-314
DEBUG:nptdms.tdms:Property wf_increment: 0.0001953125
DEBUG:nptdms.tdms:Property wf_samples: 5120
DEBUG:nptdms.tdms:Property Corrzero: 0.0
DEBUG:nptdms.tdms:Property DownSampleFactorHigh: 1
DEBUG:nptdms.tdms:Property DownSampleFactorLow: 1
DEBUG:nptdms.tdms:Property Enabled: 1
DEBUG:nptdms.tdms:Property Gain: 1.0
DEBUG:nptdms.tdms:Property NI_ChannelName: Signal 0
DEBUG:nptdms.tdms:Property NI_UnitDescription: 
DEBUG:nptdms.tdms:Property Offset: 0.0
DEBUG:nptdms.tdms:Property SensorID: 0
DEBUG:nptdms.tdms:Property wf_xname: Signal 0
DEBUG:nptdms.tdms:Property wf_xunit_string: s
DEBUG:nptdms.tdms:Reading metadata for object /'high'/'System Temp'
DEBUG:nptdms.tdms:Object data type: tdsTypeSingleFloat
DEBUG:nptdms.tdms:Object number of values in segment: 1
DEBUG:nptdms.tdms:Reading 16 properties
DEBUG:nptdms.tdms:Property wf_time_pref: absolute
DEBUG:nptdms.tdms:Property wf_start_time: 2012-01-02 10:20:32.549620
DEBUG:nptdms.tdms:Property wf_start_offset: 1.683945893e-314
DEBUG:nptdms.tdms:Property wf_increment: 1.0
DEBUG:nptdms.tdms:Property wf_samples: 1
DEBUG:nptdms.tdms:Property Corrzero: 0.0
DEBUG:nptdms.tdms:Property DownSampleFactorHigh: 5120
DEBUG:nptdms.tdms:Property DownSampleFactorLow: 5120
DEBUG:nptdms.tdms:Property Enabled: 1
DEBUG:nptdms.tdms:Property Gain: 1.0
DEBUG:nptdms.tdms:Property NI_ChannelName: System Temp
DEBUG:nptdms.tdms:Property NI_UnitDescription: 
DEBUG:nptdms.tdms:Property Offset: 0.0
DEBUG:nptdms.tdms:Property SensorID: 3
DEBUG:nptdms.tdms:Property wf_xname: System Temp
DEBUG:nptdms.tdms:Property wf_xunit_string: s
***_**************end  file -D

**Comment by lokesh422** [comment]
Hi Adam,

I have problem with datetime object while creating TDMS file. I have tried in so many ways but it could not work. Can you please help me to solve my issue. Here is my code data object working but data2 object not working

`from nptdms import TdmsWriter, RootObject, GroupObject, ChannelObject
import numpy as np
from numpy import datetime64


root_object = RootObject(properties={
    "LocoId": 40473,
    "Year": 2017,
    "Day": 10,
})
group_object = GroupObject("group_1", properties={
    "prop1": 1.2345,
    "prop2": False,
})

data = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0 ,8.0 ,9.0])
dt = np.datetime64('2005-02-25T03:30')
data2 = np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64')
print(data2)
engine_channel_object = ChannelObject("group_1", "engine_channel_object", data2, properties={
    "prop1":"lokesh",
    "prop2":"phani",
})

pneumatic_channel_object = ChannelObject("group_1", "pneumatic_channel_object", data, properties={
    "prop1":"sundeep",
    "prop2":"venkey",
})
LVE_channel_object = ChannelObject("group_1", "LVE_channel_object", data, properties={
    "prop1":"sundeep",
    "prop2":"venkey",
})
HVE_channel_object = ChannelObject("group_1", "HVE_channel_object", data, properties={
    "prop1":"sundeep",
    "prop2":"venkey",
})
vehicle_channel_object = ChannelObject("group_1", "vehicle_channel_object", data, properties={
    "prop1":"sundeep",
    "prop2":"venkey",
})
MISC_channel_object = ChannelObject("group_1", "MISC_channel_object", data, properties={
    "prop1":"sundeep",
    "prop2":"venkey",
})
datapack_channel_object = ChannelObject("group_1", "datapack_channel_object", data, properties={
    "prop1":"sundeep",
    "prop2":"venkey",
})
with TdmsWriter("phani_lokesh2.tdms") as tdms_writer:
    tdms_writer.write_segment([
        root_object,
        group_object,
        engine_channel_object,		pneumatic_channel_object,LVE_channel_object,HVE_channel_object,vehicle_channel_object,MISC_channel_object,datapack_channel_object])
    
		
`

**Comment by adamreeve** [comment]
@lokesh422 I created issue #84 for your problem

**Comment by lokesh422** [comment]
Hello Adam please check the issue #84
