### ISSUE TITLE
NotImplementedError: RTD scaling for temperatures < 0 is not implemented

### ISSUE THREAD

**Issue by jmd1979** [adamreeve/npTDMS#192]
Currently if the RTD value is less than zero the program crashes with, NotImplementedError: RTD scaling for temperatures < 0 is not implemented.

 Can the code be changed to return either NaN, or a numerical flag to indicate the temperature is less than zero?

**Comment by adamreeve** [comment]
Hi, I'd rather properly implement support for negative temperatures. I don't think this should be too difficult and it could be misleading returning NaN when the data is actually valid.

**Comment by adamreeve** [comment]
This is now supported in master and will be available in the next release.
