### ISSUE TITLE
np.float32/np.float64 are being incorrectly mapped to SingleFloatWithUnit/DoubleFloatWithUnit

### ISSUE THREAD

**Issue by adelcast** [adamreeve/npTDMS#204]
Change https://github.com/adamreeve/npTDMS/pull/173 added type declarations for SingleFloatWithUnit and DoubleFloatWithUnit of the type:

@tds_data_type(0x19, np.single)
class SingleFloatWithUnit(StructType):
    size = 8	    size = 4
    pass	    struct_declaration = "f"

the issue is that those declarations are overriding the values on the numpy_data_types dict since they come after the SingleFloat and DoubleFloat types. In the end, numpy_data_types incorrectly maps the float32/64 types to the ones with units:

dtype('int8'): <class 'nptdms.types.Int8'>, 
dtype('int16'): <class 'nptdms.types.Int16'>, 
dtype('int32'): <class 'nptdms.types.Int32'>, 
dtype('int64'): <class 'nptdms.types.Int64'>, 
dtype('uint8'): <class 'nptdms.types.Uint8'>, 
dtype('uint16'): <class 'nptdms.types.Uint16'>, 
dtype('uint32'): <class 'nptdms.types.Uint32'>, 
dtype('uint64'): <class 'nptdms.types.Uint64'>, 
dtype('float32'): <class 'nptdms.types.SingleFloatWithUnit'>, 
dtype('float64'): <class 'nptdms.types.DoubleFloatWithUnit'>,
 dtype('bool'): <class 'nptdms.types.Boolean'>, 
 dtype('complex64'): <class 'nptdms.types.ComplexSingleFloat'>,
 dtype('complex128'): <class 'nptdms.types.ComplexDoubleFloat'>

which is undesirable, since most viewers don't have support for Single/DoubleFloatWithUnit

**Comment by adamreeve** [comment]
Ah yes that was unintended, I'll fix this
