### ISSUE TITLE
corrupted data is streamed when iterating through several data_chunks() in parallel

### ISSUE THREAD

**Issue by K69rO381n1** [adamreeve/npTDMS#210]
Hi everyone :)
I have a great amount of synced data which is distributed among several channels.
Loading all the data into memory is not possible because it's too computationally heavy.
When iterating over several data_chunks() in parallel (See code snippet below) the iterators yields corrupted data (and doesn't yield as many chunks as it should).

I observed that the TdmsFile has a shared Reader object which most probably causes an index conflict (I couldn't find the exact shared variable that caused the problem)

`
Hi everyone :)
I have a great amount of synced data which is distributed among several channels.
Loading all the data into memory is not possible because it's too computationally heavy.
When iterating over several data_chunks() in parallel (See code snippet below) the iterators yields corrupted data (and doesn't yield as many chunks as it should).

I observed that the TdmsFile has a shared Reader object which most probably causes an index conflict (I couldn't find the exact shared variable that caused the problem)

the solution I found is to initiate file pointer for every channel:
```
file = 'filename.tdms'
# examples:
field1 = ('Data Group Property 1', 'Sensor_1')
field2 = ('Chennels Gourp Property', 'Channel 1')
fields = (field1, field2)

tdms_file_pointers = [nptdms.TdmsFile.open(file) for _ in range(len(fields_keys))]

for multi_channel_chunks in _multi_channel_chunk_iter(tdms_file_pointers, fields_keys, fields_labels):
   # Do your thing
   pass

for fp in tdms_file_pointers:
   fp.close()

def _multi_channel_chunk_iter(tdms_file_pointers, fields_keys, fields_labels):
   assert len(tdms_file_pointers) == len(fields_keys)
   fields = _multi_channel_attribute_extreaction(tdms_file_pointers, fields_keys)
   for ziped_chunks in zip(
         *(map(lambda field: field.data_chunks(), fields))):
      data = {label: chunk[:] for label, chunk in zip(fields_labels, ziped_chunks)}
      yield dp.DataFrame(data)

def _multi_channel_attribute_extreaction(tdms_file_pointers, fields_keys):
   return (_tdms_attribute_extraction(tdms_fp, field_keys) for tdms_fp, field_keys in zip(tdms_file_pointers, fields_keys)

def _tdms_attribute_extraction(tdms_file_pointer, field_keys):
   field_value = tdms_file_pointer
   # extracting attributes recursively.
   for key in field_keys:
      if isinstance(key, str) and key.startwith('.'):
         field_value = getattr(field_value, key[1:])
      else:
         field_value = field_value[key]
   return field_value
```

**Comment by adamreeve** [comment]
Hi, thanks for making this issue and providing a workaround. I think it's worth noting this in the documentation.

The main problem is that the reader has a file handle so seeking to a position in the file in one thread will affect reading in other threads, so there's no simple way to make this thread safe.
