### ISSUE TITLE
tdmsfile.group_channels(...) is empty 

### ISSUE THREAD

**Issue by nathanielatom** [adamreeve/npTDMS#22]
I'm working with a TDMS file which should have multiple groups for data with different lengths. Each group should have one or more channels. The command:
``tdmsfile.groups()`` gives:
``[u'22']``
However ``tdmsfile.group_channels(tdmsfile.groups()[0])`` gives an empty list.
The TDMS file was created using NI SignalExpress 2014.
file: https://dl.dropboxusercontent.com/u/42046634/Acceleration.tdms

**Comment by adamreeve** [comment]
Looks like there's a bug with how the group names are handled when they have a "/" in them and are also quoted. I can access the data if I use the correct group names, eg:
```
tdmsfile.group_channels('22/05/2015 04:18:38 PM - Acceleration - Decimated Data_Level1')
```

**Comment by adamreeve** [comment]
Should be fixed in commit 3869ce6df, and I've released a bug-fix version 0.6.4 on PyPI.

**Comment by nathanielatom** [comment]
Updated, and it worked flawlessly. Thank you for your help and ultra-quick response!

**Comment by adamreeve** [comment]
No problem, you created the issue at a good time!
