### ISSUE TITLE
iterating over goups, channels with items()

### ISSUE THREAD

**Issue by jmitrevs** [adamreeve/npTDMS#221]
Given that you can iterate, for example, with
```python
for group_name in tdms_file:
    ...
```

```python
for channel_name in group:
    ...
```
I think it would be useful to also allow:
```python
for channel_name, channel in group.items():
    ...
```
This is of course not a key feature, but I think it would be nice.

**Comment by adamreeve** [comment]
You can get something close to this with the `groups` and `channels` methods:
```python
for group in tdms_file.groups():
    group_name = group.name
    ...

for channel in group.channels():
    channel_name = channel.name
    ...
```

But I agree, this would be nice given that the `TdmsFile` and `TdmsGroup` classes already act like dictionaries in other ways.

**Comment by adamreeve** [comment]
I had a look at implementing this but have changed my mind and think the `items` approach is less clear than just using the `groups` and `channels` methods, and doesn't really add any benefit. Feel free to rely if you think I'm wrong.
