### ISSUE TITLE
Java Version of npTDMS

### ISSUE THREAD

**Issue by DwayneSmurdon** [adamreeve/npTDMS#23]
Hi Adam,

I sent an email to your old university email, but thought I'd also attempt to contact you here.  I apologize if neither is your preferred method of communication -- just let me know what is and I'll happily use it.

I am considering the development of a Java version of npTDMS, and I wanted to know if you would be able to provide some insight and advice if I do (or perhaps even contribute).
- Dwayne
- dwayne@predictabledata.com

**Comment by adamreeve** [comment]
Closing this old issue. There was a short discussion over email and some related discussion in #29 but I'm not sure if this ever came to anything. In general I'm happy to provide advice if anybody is implementing a TDMS reader.
