### ISSUE TITLE
TdmsWriter write method keyword documentation is possibly misleading

### ISSUE THREAD

**Issue by aspitarl** [adamreeve/npTDMS#261]
Hi, when I first read the[ documentation for TdmsWriter ](https://nptdms.readthedocs.io/en/stable/apireference.html#nptdms.TdmsWriter) it made me think that only the 'a' and 'w' methods are possible:

> mode – Either ‘w’ to open a new file or ‘a’ to append to an existing TDMS file.

But looking at the code it appears that this is simply just being passed into `open` so you can use it with any standard write method. 

https://github.com/adamreeve/npTDMS/blob/bf4d2f65872347fde4fe7fcbb4135f466e87323e/nptdms/writer.py#L51

I'm not sure if all the write methods work in 'bytes mode', but I was able to use it with the `a+` method anyway.  If I'm not missing something, perhaps this documentation should be improved.

**Comment by adamreeve** [comment]
Hi, thanks for opening this issue, I've now updated the documentation (it can be seen in the documentation built from the master branch [here](https://nptdms.readthedocs.io/en/latest/apireference.html#nptdms.TdmsWriter.__init__).
