### ISSUE TITLE
[Bug] read version from import lib

### ISSUE THREAD

**Issue by cunyap** [adamreeve/npTDMS#300]
With Python 3.7 the npTDMS version 1.6.2 results in an error under OSX for reading the version.

nptdms/version.py", line 1, in <module>
    from importlib import metadata

ImportError: cannot import name 'metadata' from 'importlib'. Importlib-metadata version 6.3.0. npTDMS versions < 1.6.2 do work.

**Comment by adamreeve** [comment]
Hi @cunyap, Python 3.7 is only supported for another two months, after 2023-06-27 it will reach end-of-life and receive no more security fixes. Numpy and Pandas have already dropped support for Python 3.7. So I don't think it's worth continuing support for 3.7.
