### ISSUE TITLE
API Reference

### ISSUE THREAD

**Issue by GuilleMoya** [adamreeve/npTDMS#309]
Hello, i was trying to check the API reference but this sections seems to be errased or being fixed. Can this be put back or whay is happening? Thanks a lot.

https://nptdms.readthedocs.io/en/stable/apireference.html

**Comment by adamreeve** [comment]
Hi, sorry about this, I'll take a look and get this fixed.

**Comment by adamreeve** [comment]
This has been fixed in the "latest" version docs: https://nptdms.readthedocs.io/en/latest/apireference.html

I'll make a point release shortly to fix the stable docs too.
