### ISSUE TITLE
[Feature] Option to return Dataframe as PyArrow dtype

### ISSUE THREAD

**Issue by ba05** [adamreeve/npTDMS#312]
Would be nice and may provide performance improvements if there was an option to for `as_dataframe()` to return data as a PyArrow type. See https://pandas.pydata.org/docs/user_guide/pyarrow.html

Probably would need to implement this as the Pandas Series is being built, before `DataFrame.from_dict` is called.

**Comment by adamreeve** [comment]
Alternatively, it might be more flexible if there was a method to return a PyArrow Table. That could be trivially converted to a Pandas DataFrame using Arrow types with `table.to_pandas(types_mapper=pd.ArrowDtype)`, and would be useful for other libraries that can accept Arrow data.
