### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by rubdos** [adamreeve/npTDMS#32]
Hi,

Small, but important thing I noticed when adding the LGPLv3 license on my TDMS c++ library.
You have included the LGPL additional permissions in the file LICENSE.txt.

I cite "[How to use GNU licenses for your own software](https://www.gnu.org/licenses/gpl-howto.html)" by the FSF:

> If you are releasing your program under the LGPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses so users have all the materials they need to understand their rights.

I suggest doing `mv LICENSE.txt COPYING.LESSER` and `wget https://www.gnu.org/licenses/gpl.txt -O COPYING` and committing that.

**Comment by adamreeve** [comment]
Thanks for pointing this out, I've fixed it now.
