### ISSUE TITLE
data sorting like in a table

### ISSUE THREAD

**Issue by hschabel** [adamreeve/npTDMS#332]
Hi adamreeve,

I use the TDMS format due to its abilities to have properties which can be freely defined for each channel.

These properties are used for parametering of evaluation functions.

The data section itself is used like an EXCEL Table. 

I need to find a solution to sort this like a table (in all channels exactly the same way).

In Diadem it's no problem at all, but in Python I found no solution. I have just found a function for one single channel:

```
RES = TdmsFile.read( DATEIPFAD_TDMS + ".TDMS" )
RES['group']['channel'].sort
```

Is there any option available?

Any help ist appreciated.

Regards
hschabel

**Comment by adamreeve** [comment]
Hi @hschabel, I would recommend reading the channel data into a [Pandas](https://pandas.pydata.org/) or [Polars](https://pola.rs/) DataFrame if you want to treat it like a table. You could convert the file to a Pandas DataFrame with `df = RES.as_dataframe()` for example.

**Comment by hschabel** [comment]
Hi adamreeve,

OK. This works fine. 
Thank you for your help!

Regards
