### ISSUE TITLE
tdmsinfo bug.

### ISSUE THREAD

**Issue by G-A-N** [adamreeve/npTDMS#44]
I've recently tried to run tdmsinfo on file created by LabVIEW and it crashed. If you look at the following little patch, you know why: if a channel is defined, but no data are written to it, there is no data type defined.

diff --git a/nptdms/tdmsinfo.py b/nptdms/tdmsinfo.py
index 63e5b0b..60bb7b6 100644
--- a/nptdms/tdmsinfo.py
+++ b/nptdms/tdmsinfo.py
@@ -45,7 +45,8 @@ def main():
             display("%s" % channel.path, level)
             if args.properties:
                 level = 3
-                display("data type: %s" % channel.data_type.name, level)
+                if channel.data_type != None:
+                    display("data type: %s" % channel.data_type.name, level)
                 display_properties(channel, level)

And yes, I should probably learn to use GitHub properly, but I'm too old :-)

**Comment by adamreeve** [comment]
Thanks for the fix, I've added it and released it to PyPI.
