### ISSUE TITLE
Feature Request - Add properties to TdmsObject for group and channel

### ISSUE THREAD

**Issue by mattharrigan** [adamreeve/npTDMS#46]
First, great library.  Thank you very much.  Can you please add properties for channel and group to TdmsObject?  It would useful to get those conveniently when iterating over all objects.  Currently I have ugly code to get those from the full tdms path.  If it is an object is a group only and not a channel, perhaps channel could be None.  Thanks!

**Comment by adamreeve** [comment]
Thanks for the feature request, this sounds like it would be pretty useful so I've implemented it and it's available in version 0.8.0. I still have to get the group and channel from the full path but there was already code to do that that I've reused. Let me know if you have any problems with this.
