### ISSUE TITLE
Scale Data not being applied

### ISSUE THREAD

**Issue by racingchuck** [adamreeve/npTDMS#64]
Hello,

I have been using npTDMS for while now, and I just realized that if I have only one scaling information in the metadata of a channel it does not get applied to the raw data. I saw in the code that a 1 index is used and Labview starts at zero.

Thank you,

Charles

**Comment by adamreeve** [comment]
Hi, can you provide an example of what you mean? An example file with the result you expect would be helpful. Is this for a DAQmx raw data channel? Support for DAQmx raw data was only added recently and there's limited documentation on how it works, so the current implementation probably doesn't support all the features of this type of data.

**Comment by racingchuck** [comment]
Hi,

First, thank you for the prompt response. 

When I generate the TDMS file using "TDMS Create Scaling Information" block, the scaling information is added to the channel properties. npTDMS reads the properties correctly but does not scale the data accordingly. Looking in the concerned part of [tdms.py](npTDMS/tdms.py) line 712, property checked for scaled data is 'NI_Scale[**1**]_Scale_Type'. In the file attached (scaled_tdms.tdms) you will see that the property written in the tdms file is 'NI_Scale[**0**]_Scale_Type'. At first I didn't realized the issue because I had the scaling block inside my loop which repeated the scaling information for each segment thus increment the index above 0 (see file repeated_scaling_info.tdms).

The data is not DAQMx. I expect the same result as the repeated_scaling_info.tdms file without having to keep the scaling block in the loop.

**Schema used to create scaled_tdms.tdms**
![image](https://cloud.githubusercontent.com/assets/4576528/24580396/a3657aa2-16d5-11e7-90cf-87101dd8c9d8.png)

**Schema used to create repeated_scaling_info.tdms**
![image](https://cloud.githubusercontent.com/assets/4576528/24580593/782ccfa4-16d8-11e7-8613-82073af8f018.png)


Thank you,

Charles

***I changed tdms files extension to txt for the upload ***
[repeated_scaling_info.txt](https://github.com/adamreeve/npTDMS/files/887786/repeated_scaling_info.txt)
[scaled_tdms.txt](https://github.com/adamreeve/npTDMS/files/887788/scaled_tdms.txt)

**Comment by adamreeve** [comment]
I'm not sure how this should be fixed. We could just check for any scaling property and use the first index found, but that doesn't seem correct. If there are multiple scalings, I assume they should all be applied in order, but I couldn't find any documentation to confirm this. And if I took that approach then your example where you repeatedly apply the scaling with the index incrementing each time would result in a very different result to just having one set of scaling information. I don't have access to LabView any more so can't experiment with how it handles this. Are you able to experiment and see how LabView handles multiple scalings in a TDMS file?

**Comment by racingchuck** [comment]
I have access to Labview, I'll run some tests with different scalings configuration and report the results here.

**Comment by racingchuck** [comment]
I ran a couple of different tests to isolate how Scaling Information is handled by Labview.
I made a file with two channels with raw data going from 0 to 9.

## **1: No scaling info** 

No scaling info added as a reference
![image](https://cloud.githubusercontent.com/assets/4576528/24920274/9f0a60bc-1eb4-11e7-9965-d878350237ae.png)


![image](https://cloud.githubusercontent.com/assets/4576528/24917769/3035fe92-1eac-11e7-9226-6adc3d804873.png)


## **2: Single scaling info on Channel 1**
Scaling info added on Channel 1 only, scaling infos are written in the channel properties, only Channel 1 is affected.

![image](https://cloud.githubusercontent.com/assets/4576528/24917621/c0b92d78-1eab-11e7-91ba-c5774b62dd4c.png)
![image](https://cloud.githubusercontent.com/assets/4576528/24917633/c872e568-1eab-11e7-818a-bebe1d896441.png)

## **3: Single scaling info on Group 1**
Scaling info added on Group 1 only, scaling infos are written in the group properties, all channels in group are affected.

![image](https://cloud.githubusercontent.com/assets/4576528/24917811/536d4280-1eac-11e7-913c-02f20296a014.png)
![image](https://cloud.githubusercontent.com/assets/4576528/24917821/5d805488-1eac-11e7-9dc6-a74941a0f622.png)

## **4: Single scaling info on file**
Scaling info added on file, scaling infos are written in the file properties, all channels are affected.

![image](https://cloud.githubusercontent.com/assets/4576528/24918316/fe81269a-1ead-11e7-9422-f4fec13b5a5c.png)
![image](https://cloud.githubusercontent.com/assets/4576528/24918326/04394ef0-1eae-11e7-8a05-111b0633ec04.png)

## **5: Multiple scaling info on Channel 1**
Scaling info added on Channel 1 at each iteration, scaling infos are written in the channel properties, only Channel 1 is affected, only last scaling infos are applied.


![image](https://cloud.githubusercontent.com/assets/4576528/24918864/dbc5106a-1eaf-11e7-96e8-e58f5a3c9f15.png)
![image](https://cloud.githubusercontent.com/assets/4576528/24918848/d29f343e-1eaf-11e7-8cea-60736c72b633.png)

If you want other tests or have any questions let me know.

Files (extension changed from .tdms to .txt for upload):

[no_scaling.txt](https://github.com/adamreeve/npTDMS/files/914022/no_scaling.txt)
[single_scaling_group.txt](https://github.com/adamreeve/npTDMS/files/914005/single_scaling_group.txt)
[multiple_scaling_channel.txt](https://github.com/adamreeve/npTDMS/files/914006/multiple_scaling_channel.txt)
[no_scaling.txt](https://github.com/adamreeve/npTDMS/files/914007/no_scaling.txt)
[single_scaling_channel.txt](https://github.com/adamreeve/npTDMS/files/914008/single_scaling_channel.txt)

**Comment by adamreeve** [comment]
Awesome, thanks a lot for that! I won't have time to fix this immediately but will hopefully get around to it soon.

**Comment by adamreeve** [comment]
This should be fixed in version 0.11.0 (including applying scaling from the group or the whole file)
