### ISSUE TITLE
Writing tdms files

### ISSUE THREAD

**Issue by alphazed35** [adamreeve/npTDMS#68]
Hi, 

I'm trying to write tdms files that are copies of a loaded file, but with subsets of the loaded file data. 
I figure this is the solution to the problem I raised in Issue 67, which I've closed.  Essentially I am working with large files and need to make them smaller in order to work with them effectively.  

So this is where I am at...

my loaded (300GB) tdms file has group "group" and channel "channel 1."

At the python interpreter:
`tdms_file = TdmsFile("bigFile.tdms", memmap_dir="./tmp")`
`root_object = tdms_file.object()`
`group_object = tdms_file.object('group')`
`channel_object = tdms_file.object("group","channel 1")`
`new_channel = ChannelObject("group","channel 1", channel_object.data[0:200],properties={})`
`with TdmsWriter("littleFile.tdms") as tdms_writer:`
`    tdms_writer.write_segment([root_object,group_object,new_channel])`
Gives:
`error: 'l' format requires -2147483648 <= number <= 2147483647`

At the python interpreter:
 `channel_object.data`
Gives:
`memmap([-2,  8,  0, ..., 12,  0,  0], dtype=int16)`

At the python interpreter:
`new_channel.data[0:200]` 
looks pretty good:
`memmap([ -2,   8,   0,   6,   6,  -2,  -2,  -2,  -2,  12,  -2,   6,   6,`
`        -2,  -4,   2,  10,  -4,   8,  -6,   4,   4,   6,   6,   4,  -2,`
`         4,   0,   0,   0,  -4,   0,   0,   2,   0,   4,   2,  -4, -10,`
`       -10, -12, -10,  -8, -10, -16, -10,  -4,  -8,  -2,   2,  -8,  -6,`
`         0,  -4,  -6,   6,  -6,   4,  -6,  -8,   6,  -8,  -4,  -4,   0,`
`         2,   0,   0,   2,   6,  -2,  -4,   0,   6,   8,  -4,  12,   2,`
`         8,   4,  -2,  -6,   6,   6,   2,  -2,   8,  -2,   6,   2,   2,`
`        10,  -2,   0,  -2,   4,   0,  -4, -10,   4,   4,   2,   2,   2,`
`        -6, -10,  -4,  -4,  -2, -10,  -4,  -2,  -4,   4,  -8,  -4,   2,`
`       -10,  -4,   4,   2,  -6,   4,   8,   0,   2,  10,   6,   6,  10,`
`         4,   6,   6,  -2,  10,  10,  14,   2,  16,  10,  10,   8,   8,`
`         4,  12,  14,   6,   6,   4,  10,  12,   8,  10,   2,   6,   4,`
`         4,   0,   2,   8,  -2,   8,   0,   6,   6,   2,  -2,  10, -10,`
`         8,   4,   2,   0,  12,  -6,  -4,   2,   2,   8,   0,  -4,   0,`
`         8,   2,   0,  10,   4,  10,   4,   6,   6,   8,   2,   8,   4,`
`         6,  10,   8,  10,   6], dtype=int16)`

So it looks like the memmap values are not being passed into the TdmsWrite?

Regards, 

nt

**Comment by adamreeve** [comment]
Hi, sorry for the delay in responding. I think the problem is that one of the properties in either `root_object` or `group_object` is an integer that is too big to fit in a 32 bit int. I've pushed a fix for this in version 0.11.1, can you try and see if your code now works and reopen this if you still have a problem?
