### ISSUE TITLE
Precision lost in polynomial scaling

### ISSUE THREAD

**Issue by lrthomps** [adamreeve/npTDMS#69]
The polynomial coefficients are recast as merely floats in enumerate (??). I revised the code in scaling.py for PolynomialScaling.scaling to
    scaled_data = np.polynomial.polynomial.polyval(data, self.coefficients)
and my data is now full precision (and the same as output from the propriety NI conversion software).

**Comment by adamreeve** [comment]
Hi, thanks for reporting this. This is now fixed in version 0.11.1.
