### ISSUE TITLE
how to convert any data file format(.csv, .xls, etc) to .tdms file 

### ISSUE THREAD

**Issue by iamrishab** [adamreeve/npTDMS#71]
Please help me with the code for my problem or give me some idea about the logic behind it.
Do u know  what is the difference between converting a data file to  .tdm & .tdx ratherr than converting it to .tdms?

**Comment by adamreeve** [comment]
Hi, I'm not sure what you're trying to do. You can read a csv file using Python's csv module, or an xml file using one of the packages for that purpose, then you can write to a tdms file using npTDMS as described at http://nptdms.readthedocs.io/en/stable/writing.html. npTDMS doesn't support tdm+tdx files.
