### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by rddaz2013** [adamreeve/npTDMS#79]
Hi

in the python 2 world it works fine ..now with writing .-) great job
But what is with python3?

**Comment by adamreeve** [comment]
Python 3 should work, do you have problems using nptdms with Python 3?

**Comment by rddaz2013** [comment]
With Python 3 the 'types'-word is map to a other module, i have to rename your 'types' module.  Then the unit-test are working, but I make some additional test with npTDMS in my real workflow. If the "writing" of the TDMS works I am really happy.

It looks ready to use in python3 with this small rename workaround..!

**Comment by adamreeve** [comment]
Hi, sorry for the delay in replying to this. I don't have any problem using this with python 3, and as part of the CI build tests are run on Python 3. The types library is also present in Python 2.7. When I import the types module I use `from nptdms import types` so there shouldn't be any conflict with the built in types module. Can you please provide the specific error you are getting and the code or commands you are using that reproduce this error?
