### ISSUE TITLE
assert(len(info.raw_data_widths) == 1)

### ISSUE THREAD

**Issue by lolo31370** [adamreeve/npTDMS#80]
With my TDMS file, I have this assert in tdms.py /_read_metadata (line 947).
In my case, the lenght is 3.
If I comment this line, the file is ridden but data are corrupted.

**Comment by adamreeve** [comment]
Hi, unfortunately nobody has implemented support for raw data widths > 1. I don't have the time to implement this myself but would be happy to accept pull requests to implement this.

**Comment by adamreeve** [comment]
I've looked more into the DAQmx format and made some improvements but it's not clear how to handle multiple entries in raw_data_widths, so if someone has example files and expected output that would be helpful.

**Comment by adamreeve** [comment]
Fixed in #146 and #149
