### ISSUE TITLE
1)How to test reading of tdms file using this project .  2) How can I use this project to convert tdms file into a json?

### ISSUE THREAD

**Issue by manpreet2220** [adamreeve/npTDMS#81]

**Comment by adamreeve** [comment]
Hi, what problem are you having reading a TDMS file? You should be able to follow the documentation at http://nptdms.readthedocs.io/en/stable/quickstart.html and http://nptdms.readthedocs.io/en/stable/reading.html to read a TDMS file.

As for converting to JSON, you can use the json package from the standard library to do this: https://docs.python.org/3.6/library/json.html

A numpy array isn't serializable to JSON but you can work around this by converting the arrays to list before writing json, eg:
```python
json_data = {channel.path: channel.data.tolist() for group in tdms_file.groups() for channel in tdms_file.group_channels(group)}
json_content = json.dumps(json_data)
```
This will just output the data arrays in a dictionary, but you could extend this to also include other properties of the channels and groups if you'd like.
