### ISSUE TITLE
Not able to import nptdms module.

### ISSUE THREAD

**Issue by manpreet2220** [adamreeve/npTDMS#83]
Hi,

I have created the python script to read tdms file using nptdms library . I have to call this script from java . I am using jython to run python script from java. When I am calling the script it is giving exception that "Cannot import nptdms module". I am using "from nptdms import TdmsFile" line in the script . Could you please help me. 

Below is code that I am using in java code to call the script.

    ScriptEngineManager scriptingEngineManager=new ScriptEngineManager();
    ScriptEngine scriptEngine=scriptingEngineManager.getEngineByName("python");
    System.out.print("system engine "+scriptEngine);
    scriptEngine.eval(new BufferedReader(new FileReader("demo.py")));

**Comment by adamreeve** [comment]
Sorry I can't help you with this as I'm not familiar with Jython, and it's hard to figure out what's wrong without a more detailed error message. I'm not sure that nptdms will work with Jython though, because nptdms requires numpy, which uses the Python C API.
