### ISSUE TITLE
Add workaround to as_hdf method for TypeError issue in h5py

### ISSUE THREAD

**Issue by Gygger** [adamreeve/npTDMS#88]
There's a bug in the h5py code that has been around for a while where unicode strings are not supported.  [(h5py Issue #289)](https://github.com/h5py/h5py/issues/289)

In my case, the TDMS file has strings as data so the `as_hdf` method threw an error here:
`h5file['/'+group_name+'/'+channel.channel] = channel.data`

The work around offered by dpfoose in the h5py issue comment thread worked for me.  I can open a pull request in the next couple of days.

**Comment by adamreeve** [comment]
Hi, thanks for the bug report and sorry for the delay replying, a PR to fix this would be appreciated.

**Comment by adamreeve** [comment]
Fixed in #163
