### ISSUE TITLE
Installation successful, but cannot load module

### ISSUE THREAD

**Issue by necarion** [adamreeve/npTDMS#94]
I've used the commands listed for Anaconda installation, using Root in Administrator mode.  However, python seems unable to find nptdms:
`import nptdms
Traceback (most recent call last):

  File "<ipython-input-8-0b9c68e84bf0>", line 1, in <module>
    import nptdms

ImportError: No module named nptdms`

I've reattempted installation, and get the message:
`
Requirement already satisfied: npTDMS in c:\users\NAME\appdata\local\conda\conda\envs\my_root\lib\site-packages (0.11.4)
Requirement already satisfied: numpy in c:\users\NAME\appdata\local\conda\conda\envs\my_root\lib\site-packages (from npTDMS) (1.12.1)
`

When I check, nptdms is in 
`C:\Users\NAME\AppData\Local\conda\conda\envs\my_root\Lib\site-packages`
but not in 
`C:\Users\NAME\AppData\Local\conda\conda\pkgs`

Python version 2.7.13

**Comment by adamreeve** [comment]
I'm not familiar with Conda so I'm not certain what's gone wrong here, but it might be that installing as root/admin is what is causing the problem. I would try running `pip uninstall npTDMS` as admin and then `pip install npTDMS` as your normal user.
